version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building the application"
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - '**/*'
