version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17  # Adjust as needed
    commands:
      - echo "Installing Maven"
      - yum install -y maven
      - mvn --version
  build:
    commands:
      - echo "Building the application with Maven"
      - mvn clean install -X  # Debug mode for detailed logs
artifacts:
  files:
    - '**/*'



