version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17   # Use the appropriate JDK version
    commands:
      - echo "Installing Maven"
      - yum install -y maven
  build:
    commands:
      - echo "Building with Maven"
      - mvn --quiet install
artifacts:
  files:
    - '**/*'


